# Generated by Django 5.0 on 2023-12-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('short', 'Short'), ('long', 'Long')], default='short', max_length=10),
            preserve_default=False,
        ),
    ]
